export const CONNECT = 'CONNECT';
export const SEND_TEXT = 'SEND_TEXT';

export const ON_STREAM_LOCAL = 'ON_STREAM_LOCAL';
export const ON_STREAM_REMOTE = 'ON_STREAM_REMOTE';

export const ON_OPEN_CHAT_CHANNEL = 'ON_OPEN_CHAT_CHANNEL';
export const ON_DATA_CHAT_CHANNEL = 'ON_DATA_CHAT_CHANNEL';
export const ON_CLOSE_CHAT_CHANNEL = 'ON_CLOSE_CHAT_CHANNEL';
export const ON_ERROR_CHAT_CHANNEL = 'ON_ERROR_CHAT_CHANNEL';
